const mongoose = require("mongoose");

const documentSchema = new mongoose.Schema({
    id: {
        type: Number,
        required: true,
        unique: true
    },

    title: {
        type: String,
        required: true,
        trim: true
    },

    content: {
        type: String,
        trim: true
    },

    // Topic / Section in which the document belongs
    // Example:
    // Unit 1
    // Unit 2
    // Practicals
    // Reference Material
    topic: {
        type: String,
        trim: true,
        default: "No topic"
    },

    classroom: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Classroom",
        required: true
    },

    instructor: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
        required: true
    },

    attachments: [{
        fileName: {
            type: String
        },

        fileType: {
            type: String
        },

        fileUrl: {
            type: String
        },

        // Generated by Cloudinary.
        // Used when deleting a specific file.
        publicId: {
            type: String
        }
    }],

    createdAt: {
        type: Date,
        default: Date.now
    }
});

const Document = mongoose.model("Document", documentSchema);

module.exports = Document;